/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Praktikum_22062026;

import javax.swing.JOptionPane;
public class FormPegawai extends javax.swing.JFrame {

    /**
     * Creates new form FormPegawai
     */
    public FormPegawai() {
        initComponents();
        txtGapok.setEditable(false);
        txtTunj.setEditable(false);
        txtHonor.setEditable(false);
        txtTotal.setEditable(false);
        txtPajak.setEditable(false);
        txtGaber.setEditable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrStatus = new javax.swing.ButtonGroup();
        lblTitle = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbGol = new javax.swing.JComboBox<>();
        txtNama = new javax.swing.JTextField();
        lblStatus = new javax.swing.JLabel();
        rbMenikah = new javax.swing.JRadioButton();
        rbBlMenikah = new javax.swing.JRadioButton();
        lblJam = new javax.swing.JLabel();
        txtJam = new javax.swing.JTextField();
        lblGapok = new javax.swing.JLabel();
        txtGapok = new javax.swing.JTextField();
        lblTunj = new javax.swing.JLabel();
        txtTunj = new javax.swing.JTextField();
        lblHonor = new javax.swing.JLabel();
        txtHonor = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        lblTotal = new javax.swing.JLabel();
        lblPajak = new javax.swing.JLabel();
        txtPajak = new javax.swing.JTextField();
        lblGaBer = new javax.swing.JLabel();
        txtGaber = new javax.swing.JTextField();
        btnHitung = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTitle.setText("FORM GAJI PEGAWAI");

        lblNama.setText("Nama Pegawai");

        jLabel2.setText("Golongan");

        cbGol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilihan Golongan", "Golongan 1", "Golongan 2", "Golongan 3", "Golongan 4", " " }));
        cbGol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGolActionPerformed(evt);
            }
        });

        lblStatus.setText("Status");

        btnGrStatus.add(rbMenikah);
        rbMenikah.setText("Sudah Menikah");
        rbMenikah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMenikahActionPerformed(evt);
            }
        });

        btnGrStatus.add(rbBlMenikah);
        rbBlMenikah.setText("Belum Menikah");
        rbBlMenikah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbBlMenikahActionPerformed(evt);
            }
        });

        lblJam.setText("Jam Kerja");

        lblGapok.setText("Gaji Pokok");

        lblTunj.setText("Tunjangan");

        lblHonor.setText("Honor Kerja");

        txtHonor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHonorActionPerformed(evt);
            }
        });

        lblTotal.setText("Total Gaji");

        lblPajak.setText("Pajak");

        lblGaBer.setText("Gaji Bersih");

        btnHitung.setText("Hitung");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(lblTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblTunj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblGapok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblJam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblNama, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                        .addComponent(lblHonor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblPajak, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGaBer, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbGol, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNama)
                    .addComponent(rbMenikah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtJam)
                    .addComponent(txtGapok)
                    .addComponent(txtTunj)
                    .addComponent(txtHonor)
                    .addComponent(txtTotal)
                    .addComponent(txtPajak)
                    .addComponent(txtGaber))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbBlMenikah)
                                .addGap(23, 228, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(btnKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNama)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbGol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStatus)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbMenikah)
                        .addComponent(rbBlMenikah)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJam)
                    .addComponent(txtJam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHitung))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGapok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGapok))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTunj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTunj))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHonor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHonor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGaber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPajak))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPajak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGaBer)
                    .addComponent(btnReset)
                    .addComponent(btnKeluar))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbMenikahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMenikahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbMenikahActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        try {
            String nama = txtNama.getText();
            if(nama.isEmpty()){
                JOptionPane.showMessageDialog(this,"Nama harus diisi!", "Peringatan",JOptionPane.WARNING_MESSAGE);
                txtNama.setText("");
                txtNama.requestFocus();  
            }
            double gapok = 0;
            double tunjangan = 0;
            double honor;
            double total;
            double pajak;
            double gajiBersih;
            
            switch(cbGol.getSelectedIndex()){
                case 1 : gapok = 2000000;
                         break;
                case 2 : gapok = 3000000;
                         break;
                case 3 : gapok = 4000000;
                         break;
                case 4 : gapok = 5000000;
                         break;  
                default : JOptionPane.showMessageDialog(this,"Pilih golongan terlebih dahulu ", "Peringatan", JOptionPane.WARNING_MESSAGE);
                          
            }
            
            String jamKerja = txtJam.getText();
            if (jamKerja.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Jam kerja harus diisi!","Peringatan", JOptionPane.WARNING_MESSAGE);
                txtJam.setText("");
                txtJam.requestFocus();
}

            int jam = Integer.parseInt(txtJam.getText());
            if (rbMenikah.isSelected()){
                tunjangan = gapok * 0.10;
            }else if (rbBlMenikah.isSelected()){
                tunjangan = 0;
            }else {
                JOptionPane.showMessageDialog(this,"Pilih status pegawai","Peringatan", JOptionPane.WARNING_MESSAGE);
               
            }
            
            honor = jam * 25000;
            total = gapok + tunjangan + honor;
            pajak = total * 0.025;
            gajiBersih = total - pajak;
            
            txtGapok.setText(Double.toString(gapok));
            txtTunj.setText(Double.toString(tunjangan));
            txtHonor.setText(Double.toString(honor));
            txtTotal.setText(Double.toString(total));
            txtPajak.setText(Double.toString(pajak));
            txtGaber.setText(Double.toString(gajiBersih));
        }catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,"Jam kerja harus berupa angka", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnHitungActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        int pil = JOptionPane.showConfirmDialog(this,"Apakah ingin mereset semua data?","Konfirmasi Reset",JOptionPane.YES_NO_OPTION);
        if(pil==JOptionPane.YES_NO_OPTION){
            txtNama.setText("");
            txtNama.requestFocus();
            cbGol.setSelectedIndex(0);
            txtJam.setText("");
            txtGapok.setText("");
            txtTunj.setText("");
            txtHonor.setText("");
            txtTotal.setText("");
            txtPajak.setText("");
            txtGaber.setText("");
            btnGrStatus.clearSelection();
            JOptionPane.showMessageDialog(this,"Data berhasil direset","Informasi",JOptionPane.INFORMATION_MESSAGE);
            
        }
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        int pil = JOptionPane.showConfirmDialog(this,"Apakah ingin keluar?","Konfirmasi Keluar",JOptionPane.YES_NO_OPTION);
        if(pil==JOptionPane.YES_OPTION)
            System.exit(0);
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void cbGolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbGolActionPerformed

    private void rbBlMenikahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbBlMenikahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbBlMenikahActionPerformed

    private void txtHonorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHonorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHonorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPegawai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGrStatus;
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnReset;
    private javax.swing.JComboBox<String> cbGol;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblGaBer;
    private javax.swing.JLabel lblGapok;
    private javax.swing.JLabel lblHonor;
    private javax.swing.JLabel lblJam;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblPajak;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTunj;
    private javax.swing.JRadioButton rbBlMenikah;
    private javax.swing.JRadioButton rbMenikah;
    private javax.swing.JTextField txtGaber;
    private javax.swing.JTextField txtGapok;
    private javax.swing.JTextField txtHonor;
    private javax.swing.JTextField txtJam;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtPajak;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTunj;
    // End of variables declaration//GEN-END:variables
}
