/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Praktikum_29062026;

import java.awt.HeadlessException;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS VIVOBOOK
 */
public class FormMinuman extends javax.swing.JFrame {

    private FormUtama utama;
    public FormMinuman() {
        initComponents();
    }

    public FormMinuman(FormUtama utama) throws HeadlessException {
        this.utama = utama;
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbkTehTarik = new javax.swing.JCheckBox();
        cbkJusJeruk = new javax.swing.JCheckBox();
        cbkEsTeh = new javax.swing.JCheckBox();
        txtTehTarik = new javax.swing.JTextField();
        txtJusJeruk = new javax.swing.JTextField();
        txtEsTeh = new javax.swing.JTextField();
        cbTehTarik = new javax.swing.JComboBox<>();
        cbJusJeruk = new javax.swing.JComboBox<>();
        cbEsTeh = new javax.swing.JComboBox<>();
        txtTotTehTarik = new javax.swing.JTextField();
        txtTotJusJeruk = new javax.swing.JTextField();
        txtTotEsTeh = new javax.swing.JTextField();
        btnTotal = new javax.swing.JButton();
        txtTotalMinuman = new javax.swing.JTextField();
        btnKembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel1.setText("PILIHAN MENU MINUMAN");

        cbkTehTarik.setText("Teh Tarik");
        cbkTehTarik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbkTehTarikActionPerformed(evt);
            }
        });

        cbkJusJeruk.setText("Jus Jeruk");
        cbkJusJeruk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbkJusJerukActionPerformed(evt);
            }
        });

        cbkEsTeh.setText("Es Teh ");
        cbkEsTeh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbkEsTehActionPerformed(evt);
            }
        });

        txtTehTarik.setText("0");
        txtTehTarik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTehTarikActionPerformed(evt);
            }
        });

        txtJusJeruk.setText("0");
        txtJusJeruk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJusJerukActionPerformed(evt);
            }
        });

        txtEsTeh.setText("0");
        txtEsTeh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEsTehActionPerformed(evt);
            }
        });

        cbTehTarik.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbTehTarik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTehTarikActionPerformed(evt);
            }
        });

        cbJusJeruk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbJusJeruk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJusJerukActionPerformed(evt);
            }
        });

        cbEsTeh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbEsTeh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEsTehActionPerformed(evt);
            }
        });

        txtTotTehTarik.setText("0");

        txtTotJusJeruk.setText("0");

        txtTotEsTeh.setText("0");

        btnTotal.setText("Total");
        btnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalActionPerformed(evt);
            }
        });

        txtTotalMinuman.setText("0");

        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(302, 302, 302)
                                .addComponent(btnTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cbkEsTeh, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtEsTeh, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(cbkJusJeruk, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtJusJeruk, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(cbkTehTarik, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(txtTehTarik, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cbTehTarik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbJusJeruk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbEsTeh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTotTehTarik, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                            .addComponent(txtTotJusJeruk)
                            .addComponent(txtTotEsTeh, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTotalMinuman))))
                .addGap(90, 90, 90))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnKembali)
                .addGap(256, 256, 256))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbkTehTarik)
                    .addComponent(txtTehTarik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTehTarik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotTehTarik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbkJusJeruk)
                    .addComponent(txtJusJeruk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbJusJeruk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotJusJeruk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbkEsTeh)
                    .addComponent(txtEsTeh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbEsTeh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotEsTeh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTotal)
                    .addComponent(txtTotalMinuman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addComponent(btnKembali)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTehTarikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTehTarikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTehTarikActionPerformed

    private void txtJusJerukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJusJerukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJusJerukActionPerformed

    private void txtEsTehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEsTehActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEsTehActionPerformed

    private void cbTehTarikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTehTarikActionPerformed
        int jumlah = (int) cbTehTarik.getSelectedIndex();
        double harga =Double.parseDouble(txtTehTarik.getText());
        double total = jumlah*harga;
        txtTotTehTarik.setText(Double.toString(total));
    }//GEN-LAST:event_cbTehTarikActionPerformed

    private void cbJusJerukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJusJerukActionPerformed
        int jumlah = (int) cbJusJeruk.getSelectedIndex();
        double harga =Double.parseDouble(txtJusJeruk.getText());
        double total = jumlah*harga;
        txtTotJusJeruk.setText(Double.toString(total));
    }//GEN-LAST:event_cbJusJerukActionPerformed

    private void cbEsTehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEsTehActionPerformed
        int jumlah = (int) cbEsTeh.getSelectedIndex();
        double harga =Double.parseDouble(txtEsTeh.getText());
        double total = jumlah*harga;
        txtTotEsTeh.setText(Double.toString(total));
    }//GEN-LAST:event_cbEsTehActionPerformed

    private void btnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalActionPerformed
        if (cbkTehTarik.isSelected() && cbTehTarik.getSelectedIndex() == 0) {JOptionPane.showMessageDialog(this,
            "Silakan pilih jumlah Teh Tarik","Peringatan",JOptionPane.WARNING_MESSAGE);
            cbTehTarik.requestFocus();
        }

        if (cbkJusJeruk.isSelected() && cbJusJeruk.getSelectedIndex() == 0) {JOptionPane.showMessageDialog(this,
            "Silakan pilih jumlah Jus Jeruk","Peringatan",JOptionPane.WARNING_MESSAGE);
            cbJusJeruk.requestFocus();
        }

        if (cbkEsTeh.isSelected() && cbEsTeh.getSelectedIndex() == 0) {JOptionPane.showMessageDialog(this,
            "Silakan pilih jumlah Es Teh","Peringatan",JOptionPane.WARNING_MESSAGE);
            cbEsTeh.requestFocus();
        }
        double a = Double.parseDouble(txtTotTehTarik.getText());
        double b = Double.parseDouble(txtTotJusJeruk.getText());
        double c = Double.parseDouble(txtTotEsTeh.getText());
        double total = a+b+c;
        txtTotalMinuman.setText(Double.toString(total));
    }//GEN-LAST:event_btnTotalActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        String total = txtTotalMinuman.getText();
        utama.setTotalMinuman(total);
        this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void cbkTehTarikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbkTehTarikActionPerformed
        txtTehTarik.setText("7000");
    }//GEN-LAST:event_cbkTehTarikActionPerformed

    private void cbkJusJerukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbkJusJerukActionPerformed
        txtJusJeruk.setText("8000");
    }//GEN-LAST:event_cbkJusJerukActionPerformed

    private void cbkEsTehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbkEsTehActionPerformed
        txtEsTeh.setText("5000");
    }//GEN-LAST:event_cbkEsTehActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMinuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMinuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMinuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMinuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMinuman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnTotal;
    private javax.swing.JComboBox<String> cbEsTeh;
    private javax.swing.JComboBox<String> cbJusJeruk;
    private javax.swing.JComboBox<String> cbTehTarik;
    private javax.swing.JCheckBox cbkEsTeh;
    private javax.swing.JCheckBox cbkJusJeruk;
    private javax.swing.JCheckBox cbkTehTarik;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtEsTeh;
    private javax.swing.JTextField txtJusJeruk;
    private javax.swing.JTextField txtTehTarik;
    private javax.swing.JTextField txtTotEsTeh;
    private javax.swing.JTextField txtTotJusJeruk;
    private javax.swing.JTextField txtTotTehTarik;
    private javax.swing.JTextField txtTotalMinuman;
    // End of variables declaration//GEN-END:variables
}
