/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Praktikum_29062026;

import javax.swing.JOptionPane;

/**
 *
 * @author ASUS VIVOBOOK
 */
public class FormMakanan extends javax.swing.JFrame {

   private FormUtama utama;
   
    public FormMakanan() {
        initComponents();
    }

    public FormMakanan(FormUtama utama) {
        this.utama = utama;
        initComponents();
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblJudul = new javax.swing.JLabel();
        ckbNasgor = new javax.swing.JCheckBox();
        ckbMiegor = new javax.swing.JCheckBox();
        ckbMiere = new javax.swing.JCheckBox();
        txtNasgor = new javax.swing.JTextField();
        txtMiegor = new javax.swing.JTextField();
        txtMiere = new javax.swing.JTextField();
        cbNasgor = new javax.swing.JComboBox<>();
        cbMiegor = new javax.swing.JComboBox<>();
        cbMiere = new javax.swing.JComboBox<>();
        txtTotNasgor = new javax.swing.JTextField();
        txtTotMiegor = new javax.swing.JTextField();
        txtTotMiere = new javax.swing.JTextField();
        txtTotalMakanan = new javax.swing.JTextField();
        btnKembali = new javax.swing.JButton();
        btnTotal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblJudul.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblJudul.setText("PILIHAN MENU MAKANAN");

        ckbNasgor.setText("Nasi Goreng");
        ckbNasgor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbNasgorActionPerformed(evt);
            }
        });

        ckbMiegor.setText("Mie Goreng");
        ckbMiegor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbMiegorActionPerformed(evt);
            }
        });

        ckbMiere.setText("Mie Rebus");
        ckbMiere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbMiereActionPerformed(evt);
            }
        });

        txtNasgor.setText("0");
        txtNasgor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNasgorActionPerformed(evt);
            }
        });

        txtMiegor.setText("0");
        txtMiegor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMiegorActionPerformed(evt);
            }
        });

        txtMiere.setText("0");
        txtMiere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMiereActionPerformed(evt);
            }
        });

        cbNasgor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbNasgor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNasgorActionPerformed(evt);
            }
        });

        cbMiegor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbMiegor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMiegorActionPerformed(evt);
            }
        });

        cbMiere.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbMiere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMiereActionPerformed(evt);
            }
        });

        txtTotNasgor.setText("0");
        txtTotNasgor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotNasgorActionPerformed(evt);
            }
        });

        txtTotMiegor.setText("0");

        txtTotMiere.setText("0");

        txtTotalMakanan.setText("0");

        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        btnTotal.setText("Total");
        btnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ckbMiegor)
                    .addComponent(ckbNasgor)
                    .addComponent(ckbMiere))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNasgor, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMiegor, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMiere, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbNasgor, 0, 76, Short.MAX_VALUE)
                            .addComponent(cbMiegor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbMiere, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTotalMakanan, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                            .addComponent(txtTotMiere)
                            .addComponent(txtTotMiegor)
                            .addComponent(txtTotNasgor)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblJudul)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(114, 114, 114))
            .addGroup(layout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addComponent(btnKembali)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblJudul)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbNasgor)
                    .addComponent(txtNasgor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbNasgor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotNasgor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbMiegor)
                    .addComponent(txtMiegor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMiegor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotMiegor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbMiere)
                    .addComponent(txtMiere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMiere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotMiere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalMakanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTotal))
                .addGap(65, 65, 65)
                .addComponent(btnKembali)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ckbMiegorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbMiegorActionPerformed
        txtMiegor.setText("10000");
    }//GEN-LAST:event_ckbMiegorActionPerformed

    private void txtNasgorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNasgorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNasgorActionPerformed

    private void txtMiegorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMiegorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMiegorActionPerformed

    private void txtMiereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMiereActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMiereActionPerformed

    private void ckbNasgorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbNasgorActionPerformed
        txtNasgor.setText("15000");
    }//GEN-LAST:event_ckbNasgorActionPerformed

    private void ckbMiereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbMiereActionPerformed
        txtMiere.setText("8000");
    }//GEN-LAST:event_ckbMiereActionPerformed

    private void cbNasgorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNasgorActionPerformed
        int jumlah = (int) cbNasgor.getSelectedIndex();
        double harga =Double.parseDouble(txtNasgor.getText());
        double total = jumlah*harga;
        txtTotNasgor.setText(Double.toString(total));
    }//GEN-LAST:event_cbNasgorActionPerformed

    private void cbMiegorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMiegorActionPerformed
        int jumlah = (int) cbMiegor.getSelectedIndex();
        double harga =Double.parseDouble(txtMiegor.getText());
        double total = jumlah*harga;
        txtTotMiegor.setText(Double.toString(total));
    }//GEN-LAST:event_cbMiegorActionPerformed

    private void cbMiereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMiereActionPerformed
        int jumlah = (int) cbMiere.getSelectedIndex();
        double harga =Double.parseDouble(txtMiere.getText());
        double total = jumlah*harga;
        txtTotMiere.setText(Double.toString(total));
    }//GEN-LAST:event_cbMiereActionPerformed

    private void btnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalActionPerformed
        if (ckbNasgor.isSelected() && cbNasgor.getSelectedIndex() == 0) {JOptionPane.showMessageDialog(this,
            "Silakan pilih jumlah Nasi Goreng","Peringatan",JOptionPane.WARNING_MESSAGE);
            cbNasgor.requestFocus();
        }

        if (ckbMiegor.isSelected() && cbMiegor.getSelectedIndex() == 0) {JOptionPane.showMessageDialog(this,
            "Silakan pilih jumlah Mie Goreng","Peringatan",JOptionPane.WARNING_MESSAGE);
            cbMiegor.requestFocus();
        }

        if (ckbMiere.isSelected() && cbMiere.getSelectedIndex() == 0) {JOptionPane.showMessageDialog(this,
            "Silakan pilih jumlah Mie Rebus","Peringatan",JOptionPane.WARNING_MESSAGE);
            cbMiere.requestFocus();
        }
        double a = Double.parseDouble(txtTotNasgor.getText());
        double b = Double.parseDouble(txtTotMiegor.getText());
        double c = Double.parseDouble(txtTotMiere.getText());
        double total = a+b+c;
        txtTotalMakanan.setText(Double.toString(total));
    }//GEN-LAST:event_btnTotalActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        String total = txtTotalMakanan.getText();
        utama.setTotalMakanan(total);
        this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void txtTotNasgorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotNasgorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotNasgorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMakanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnTotal;
    private javax.swing.JComboBox<String> cbMiegor;
    private javax.swing.JComboBox<String> cbMiere;
    private javax.swing.JComboBox<String> cbNasgor;
    private javax.swing.JCheckBox ckbMiegor;
    private javax.swing.JCheckBox ckbMiere;
    private javax.swing.JCheckBox ckbNasgor;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JTextField txtMiegor;
    private javax.swing.JTextField txtMiere;
    private javax.swing.JTextField txtNasgor;
    private javax.swing.JTextField txtTotMiegor;
    private javax.swing.JTextField txtTotMiere;
    private javax.swing.JTextField txtTotNasgor;
    private javax.swing.JTextField txtTotalMakanan;
    // End of variables declaration//GEN-END:variables
}
