/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Praktikum_15062026;

import javax.swing.JOptionPane;

/**
 *
 * @author ASUS VIVOBOOK
 */
public class FormPenilaian extends javax.swing.JFrame {

    /**
     * Creates new form FormPenilaian
     */
    public FormPenilaian() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblJudul = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblKelas = new javax.swing.JLabel();
        lblMatkul = new javax.swing.JLabel();
        lblTugas = new javax.swing.JLabel();
        lblQuiz = new javax.swing.JLabel();
        lblUts = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtKelas = new javax.swing.JTextField();
        txtMatkul = new javax.swing.JTextField();
        txtTugas = new javax.swing.JTextField();
        txtQuiz = new javax.swing.JTextField();
        txtUts = new javax.swing.JTextField();
        btnProses = new javax.swing.JButton();
        lblNilaiAkhir = new javax.swing.JLabel();
        txtNilaiAkhir = new javax.swing.JTextField();
        lblUas = new javax.swing.JLabel();
        txtUas = new javax.swing.JTextField();
        lblKonversi = new javax.swing.JLabel();
        txtKonversi = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblJudul.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblJudul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJudul.setText("FORM PENILAIAN MAHASISWA");

        jLabel1.setText("Nama Mahasiswa");

        lblKelas.setText("Kelas");

        lblMatkul.setText("Mata Kuliah");

        lblTugas.setText("Nilai Tugas");

        lblQuiz.setText("Nilai Quiz");

        lblUts.setText("Nilai UTS");

        txtKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKelasActionPerformed(evt);
            }
        });

        txtMatkul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatkulActionPerformed(evt);
            }
        });

        txtTugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTugasActionPerformed(evt);
            }
        });

        btnProses.setText("Proses");
        btnProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesActionPerformed(evt);
            }
        });

        lblNilaiAkhir.setText("Nilai Akhir");

        txtNilaiAkhir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNilaiAkhirActionPerformed(evt);
            }
        });

        lblUas.setText("Nilai UAS");

        lblKonversi.setText("Konversi Nilai");

        txtKonversi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKonversiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblMatkul)
                                    .addGap(47, 47, 47)
                                    .addComponent(txtMatkul))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(lblKelas))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGap(13, 13, 13)
                                            .addComponent(txtKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblUas)
                                        .addGap(61, 61, 61)
                                        .addComponent(txtUas, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblTugas)
                                            .addComponent(lblQuiz)
                                            .addComponent(lblUts))
                                        .addGap(50, 50, 50)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtQuiz, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                            .addComponent(txtUts)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtTugas)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblNilaiAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtNilaiAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnProses, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblKonversi)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtKonversi, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(lblJudul)))
                .addGap(83, 83, 83))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblKonversi)
                        .addComponent(txtKonversi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblKelas)
                            .addComponent(txtKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMatkul)
                            .addComponent(txtMatkul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTugas)
                            .addComponent(txtTugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblQuiz)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnProses)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUts)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtUts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNilaiAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblNilaiAkhir)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUas)
                            .addComponent(txtUas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(138, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKelasActionPerformed

    private void txtMatkulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatkulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatkulActionPerformed

    private void txtTugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTugasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTugasActionPerformed

    private void txtNilaiAkhirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNilaiAkhirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNilaiAkhirActionPerformed

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
        String nama = txtNama.getText();
        String kelas = txtKelas.getText();
        String matkul = txtMatkul.getText();
        
        if(nama.isEmpty()){
            JOptionPane.showMessageDialog(this,"Nama harus diisi!", "Peringatan",JOptionPane.WARNING_MESSAGE);
            txtNama.setText(""); 
            txtNama.requestFocus();  
        }
        
        if(kelas.isEmpty()){
            JOptionPane.showMessageDialog(this,"Kelas harus diisi!", "Peringatan",JOptionPane.WARNING_MESSAGE);
            txtKelas.setText("");
            txtKelas.requestFocus();
        }
        
        if(matkul.isEmpty()){
            JOptionPane.showMessageDialog(this,"Mata Kuliah harus diisi", "Peringatan",JOptionPane.WARNING_MESSAGE);
            txtMatkul.setText("");
            txtMatkul.requestFocus();
         
        }
        
        if (txtTugas.getText().isEmpty() || txtQuiz.getText().isEmpty() ||
            txtUts.getText().isEmpty() || txtUas.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,"Semua nilai harus diisi","Peringatan",JOptionPane.WARNING_MESSAGE);
        return;
    }
        try {
        double tugas = validasiNilai(txtTugas.getText(),"Tugas");
        double quiz = validasiNilai(txtQuiz.getText(),"Quiz");
        double uts = validasiNilai(txtUts.getText(),"UTS");
        double uas = validasiNilai(txtUas.getText(),"UAS");
        
        double na = 0.15*tugas + 0.2*quiz + 0.3*uts + 0.35*uas;
        
        txtNilaiAkhir.setText(Double.toString(na));
        txtKonversi.setText(KonversiNilai(na));
        
        JOptionPane.showMessageDialog(this, "Nama : "+nama+
                                            "\nkelas : "+kelas+
                                            "\nMata Kuliah : "+matkul+
                                            "\nNilaiAkhir : "+na+
                                            "\nKonversi Nilai : "+KonversiNilai(na),
                                            "Hasil Penilaian",JOptionPane.INFORMATION_MESSAGE);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage(), "Validasi Nilai",JOptionPane.ERROR_MESSAGE);
            
        }
    }//GEN-LAST:event_btnProsesActionPerformed

    private void txtKonversiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKonversiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKonversiActionPerformed

    private double validasiNilai(String input, String jenisNilai) throws Exception {
        double nilai = Double.parseDouble(input);
        if(nilai <0 || nilai > 100)
            throw new Exception (jenisNilai+ " harus antara 0 - 100");
        return nilai;    
            
    }
    
    private String KonversiNilai(double nilai) {
        if (nilai >= 80 && nilai <= 100) {
            return "A";
        } else if (nilai >= 65) {
            return "B";
        } else if (nilai >= 55) {
            return "C";
        } else {
            return "D";
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPenilaian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPenilaian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPenilaian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPenilaian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPenilaian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProses;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblKelas;
    private javax.swing.JLabel lblKonversi;
    private javax.swing.JLabel lblMatkul;
    private javax.swing.JLabel lblNilaiAkhir;
    private javax.swing.JLabel lblQuiz;
    private javax.swing.JLabel lblTugas;
    private javax.swing.JLabel lblUas;
    private javax.swing.JLabel lblUts;
    private javax.swing.JTextField txtKelas;
    private javax.swing.JTextField txtKonversi;
    private javax.swing.JTextField txtMatkul;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNilaiAkhir;
    private javax.swing.JTextField txtQuiz;
    private javax.swing.JTextField txtTugas;
    private javax.swing.JTextField txtUas;
    private javax.swing.JTextField txtUts;
    // End of variables declaration//GEN-END:variables
}
